[project]
name = 'digital-art-marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.marketplace]
path = 'contracts/marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.nft-minting]
path = 'contracts/nft-minting.clar'
clarity_version = 2
epoch = 2.5

[contracts.royalty-splitter]
path = 'contracts/royalty-splitter.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
